apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: middleware
spec:
  storageClassName: mysqlgp2
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: middleware
  storageClassName: mysqlgp2
  labels:
    app: digitbankmysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysqlgp2
  resources:
    requests:
      storage: 20Gi

