apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: middleware
  labels:
    app: digitbankmysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysqlgp2 
  resources:
    requests:
      storage: 20Gi
