apiVersion: v1
kind: Service
metadata:
  name: digitbank-mysql
  namespace: middleware 
  labels:
    app: digitbankmysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: digitbankmysql
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: digitbank-mysql
  namespace: middleware
  labels:
    app: digitbankmysql
spec:
  selector:
    matchLabels:
      app: digitbankmysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: digitbankmysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-tb7d6bc5g6 
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: "6000m"
            memory: 20Gi
          requests:
            cpu: "3000m"
            memory: 10Gi
            #     nodeSelector:
            #    disktype: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
